### ISSUE TITLE
Problema con la gema crono

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#131]
Al correr la tarea de activejob sale el error:

```shell
bundle exec crono RAILS_ENV=development
uninitialized constant ActiveJob
/home/jroa/Documents/lapapaya/l/app/jobs/check_merit_rules_job.rb:1:in `<top (required)>'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/railties-4.1.0/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/railties-4.1.0/lib/rails/engine.rb:467:in `each'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/railties-4.1.0/lib/rails/engine.rb:467:in `block in eager_load!'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/railties-4.1.0/lib/rails/engine.rb:465:in `each'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/railties-4.1.0/lib/rails/engine.rb:465:in `eager_load!'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/crono-0.9.0/lib/crono/cli.rb:74:in `load_rails'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/crono-0.9.0/lib/crono/cli.rb:23:in `run'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/gems/crono-0.9.0/exe/crono:8:in `<top (required)>'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/bin/crono:23:in `load'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/bin/crono:23:in `<main>'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/bin/ruby_executable_hooks:15:in `eval'
/home/jroa/.rvm/gems/ruby-2.0.0-p643@lapapaya/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by roadev** [comment]
Se debe actualizar a rails 4.1.0 e instalar la gema ActiveJob 0

**Comment by roadev** [comment]
Fixed with ab9c7e1622140e48f621640ae7d24421076a28e3
